## Lesson 5: `.str` and `.dt` accessor

In [170]:
import numpy as np
import pandas as pd

In [171]:
data = pd.Series(['peter', 'Paul', None, 'MARY', 'gUIDO'])
print(data)
# This would fail with a standard loop
#[s.capitalize() for s in data] # -> Raises an error because of None
# The correct way with Pandas
print(data.str.capitalize())

0    peter
1     Paul
2     None
3     MARY
4    gUIDO
dtype: object
0    Peter
1     Paul
2     None
3     Mary
4    Guido
dtype: object

In [172]:
data.str.upper()

0    PETER
1     PAUL
2     None
3     MARY
4    GUIDO
dtype: object

In [173]:
data.str.lower()

0    peter
1     paul
2     None
3     mary
4    guido
dtype: object

In [174]:
data.str.split("a")

0    [peter]
1    [P, ul]
2       None
3     [MARY]
4    [gUIDO]
dtype: object

In [175]:
data.str.strip()

0    peter
1     Paul
2     None
3     MARY
4    gUIDO
dtype: object

In [176]:
s = pd.Series([' house ', 'kitchen', 'BATHROOM '])
# Case normalization
print("Upper case:\n", s.str.upper())
# Stripping whitespace
print("\nStripped:\n", s.str.strip())
# Replacing strings
print("\nReplaced:\n", s.str.replace(' ', '_'))

Upper case:
 0       HOUSE
1      KITCHEN
2    BATHROOM
dtype: object

Stripped:
 0       house
1     kitchen
2    BATHROOM
dtype: object

Replaced:
 0      _house_
1      kitchen
2    BATHROOM_
dtype: object

In [177]:
s = pd.Series(['apple', 'banana', 'apricot', 'blueberry'])

# Check for substring existence (case-insensitive)
print("Contains 'A' (case-insensitive):\n", s.str.contains('A', case=False))

# Check if string starts with...
print("\nStarts with 'a':\n", s.str.startswith('a'))

# Check if string ends with...
print("\nEnds with 't':\n", s.str.endswith('t'))

Contains 'A' (case-insensitive):
 0     True
1     True
2     True
3    False
dtype: bool

Starts with 'a':
 0     True
1    False
2     True
3    False
dtype: bool

Ends with 't':
 0    False
1    False
2     True
3    False
dtype: bool

In [178]:
df_lab1 = pd.DataFrame({
    'full_name': [' John Smith ', 'Jane Doe', '  peter jones  '],
    'location': ['123 Main St, New York, USA', '456 Oak Ave, London, UK', '789 Pine Ln, New York, USA']
})
df_lab1

         full_name                    location
0      John Smith   123 Main St, New York, USA
1         Jane Doe     456 Oak Ave, London, UK
2    peter jones    789 Pine Ln, New York, USA

In [179]:
df_lab1['cleaned_name'] = df_lab1['full_name'].str.strip().str.title()
print(df_lab1['cleaned_name'])

0     John Smith
1       Jane Doe
2    Peter Jones
Name: cleaned_name, dtype: object

In [180]:
my_customer = df_lab1[df_lab1['location'].str.contains('New York')]
print(my_customer)

         full_name                    location cleaned_name
0      John Smith   123 Main St, New York, USA   John Smith
2    peter jones    789 Pine Ln, New York, USA  Peter Jones

In [181]:
df_lab1[['street','city','country']] = df_lab1['location'].str.split(',', expand=True) 
df_lab1

,full_name,location,cleaned_name,street,city,country
0,John Smith,"123 Main St, New York, USA",John Smith,123 Main St,New York,USA
1,Jane Doe,"456 Oak Ave, London, UK",Jane Doe,456 Oak Ave,London,UK
2,peter jones,"789 Pine Ln, New York, USA",Peter Jones,789 Pine Ln,New York,USA

In [182]:
df_lab1['location'].str.split(',', expand=False)

0    [123 Main St,  New York,  USA]
1       [456 Oak Ave,  London,  UK]
2    [789 Pine Ln,  New York,  USA]
Name: location, dtype: object

In [183]:
s = pd.Series(['Apple', 'Banana', 'apricot', 'Avocado'])
# Without flags (case-sensitive)
# Checks if the string STARTS with 'A'
print("Starts with 'A' (case-sensitive):\n", s.str.match(r'A.*'))

Starts with 'A' (case-sensitive):
 0     True
1    False
2    False
3     True
dtype: bool

In [184]:
import re
print(s) 
# With flags (case-insensitive)
# Checks if the string STARTS with 'a' or 'A'
print("\nStarts with 'a' (case-insensitive):\n", s.str.match(r'a.*',flags=re.IGNORECASE))

0      Apple
1     Banana
2    apricot
3    Avocado
dtype: object

Starts with 'a' (case-insensitive):
 0     True
1    False
2     True
3     True
dtype: bool

In [185]:
s = pd.Series(['ID: A123', 'id: b456', 'No ID here'])
# Without flags (case-sensitive) - will miss 'id: b456'
print("Extract number after 'ID: ':\n", s.str.extract(r'ID: [A-Z](\d+)'))
# With flags (case-insensitive)
print("\nExtract number after 'id: ' (case-insensitive):\n", s.str.extract(r'id: [a-z](\d+)', flags=re.I))

Extract number after 'ID: ':
      0
0  123
1  NaN
2  NaN

Extract number after 'id: ' (case-insensitive):
      0
0  123
1  456
2  NaN

In [186]:
s = pd.Series(['#sale #promo', '#Sale #new', '#shipping'])
# Without flags (case-sensitive) - finds only lowercase hashtags
print("Find all lowercase hashtags:\n", s.str.findall(r'#([a-z]+)'))
print("Find all lowercase hashtags:\n", s.str.extract(r'#([a-z]+)'))

Find all lowercase hashtags:
 0    [sale, promo]
1            [new]
2       [shipping]
dtype: object
Find all lowercase hashtags:
           0
0      sale
1       new
2  shipping

In [187]:
# With flags (case-insensitive) - finds all hashtags
print("\nFind all hashtags (case-insensitive):\n", s.str.findall(r'#([a-z]+)', flags=re.IGNORECASE))

Find all hashtags (case-insensitive):
 0    [sale, promo]
1      [Sale, new]
2       [shipping]
dtype: object

In [188]:
df_comments = pd.DataFrame({ 'comments': [
'REF-1234: Great product!',
'Complaint: The item (REF-5678) was broken.',
'REF-9101, love it! #awesome #greatbuy',
'This is not a valid comment',
'complaint: another issue with REF-1122']})

In [189]:
df_comments['is_valid'] = df_comments['comments'].str.match(r'(REF|Complaint).*')
df_comments

                                     comments  is_valid
0                    REF-1234: Great product!      True
1  Complaint: The item (REF-5678) was broken.      True
2       REF-9101, love it! #awesome #greatbuy      True
3                 This is not a valid comment     False
4      complaint: another issue with REF-1122     False

In [190]:
complaints_df = pd.DataFrame
complaints_df = df_comments[df_comments['comments'].str.contains('complaint', flags = re.I)]
complaints_df

                                     comments  is_valid
1  Complaint: The item (REF-5678) was broken.      True
4      complaint: another issue with REF-1122     False

In [191]:
df_comments['ref_id'] = df_comments['comments'].str.extract(r'-(\d+)')
df_comments

                                     comments  is_valid ref_id
0                    REF-1234: Great product!      True   1234
1  Complaint: The item (REF-5678) was broken.      True   5678
2       REF-9101, love it! #awesome #greatbuy      True   9101
3                 This is not a valid comment     False    NaN
4      complaint: another issue with REF-1122     False   1122

In [192]:
df_comments['hastag'] = df_comments['comments'].str.findall(r'#(\w+)')
df_comments

,comments,is_valid,ref_id,hastag
0,REF-1234: Great product!,True,1234,[]
1,Complaint: The item (REF-5678) was broken.,True,5678,[]
2,"REF-9101, love it! #awesome #greatbuy",True,9101,"[awesome, greatbuy]"
3,This is not a valid comment,False,NaN,[]
4,complaint: another issue with REF-1122,False,1122,[]

In [193]:
# Convert strings to datetime, Pandas can often infer the format
dates_str = ['2023-01-01', '2023/01/02', '05-Jan-2023','24/12/2024']
dates = pd.to_datetime(dates_str,format="mixed", dayfirst= True)
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-05', '2024-12-24'], dtype='datetime64[ns]', freq=None)

In [194]:
# Handle errors: coerce invalid values to NaT (Not a Time)
bad_dates = ['2023-01-01', 'not a date']
# The errors='coerce' parameter will turn any unparseable date into NaT (Not a Time),
# which is Pandas' equivalent of NaN for datetime objects. This prevents the code from crashing.
print(pd.to_datetime(bad_dates, errors='coerce'))

DatetimeIndex(['2023-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)

In [195]:
df = pd.DataFrame({
    'sale_date': pd.to_datetime(['2023-01-15', '2023-01-16']),
    'sales': [100, 150]
})
print("--- Before setting index ---")
print(df.info())
df

--- Before setting index ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sale_date  2 non-null      datetime64[ns]
 1   sales      2 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 164.0 bytes
None

   sale_date  sales
0 2023-01-15    100
1 2023-01-16    150

In [196]:
# Set the 'sale_date' column as the index
df.set_index('sale_date', inplace=True)
print("\n--- After setting index ---")
print(df.info())
print("\nIndex Type:", type(df.index))

--- After setting index ---
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2 entries, 2023-01-15 to 2023-01-16
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sales   2 non-null      int64
dtypes: int64(1)
memory usage: 32.0 bytes
None

Index Type: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [197]:
ts = pd.Series(np.random.randn(1000),
               index=pd.date_range('1/1/2020', periods=1000))
ts.head()

2020-01-01    1.075837
2020-01-02   -0.453008
2020-01-03   -1.384070
2020-01-04    0.742903
2020-01-05   -0.339073
Freq: D, dtype: float64

In [198]:
ts['2021'].head()

2021-01-01    0.289176
2021-01-02   -1.023528
2021-01-03   -0.879797
2021-01-04   -1.943766
2021-01-05    2.251982
Freq: D, dtype: float64

In [199]:


# Select a month
print(ts['2021-05'].head())

2021-05-01   -0.093307
2021-05-02    0.379042
2021-05-03   -0.357718
2021-05-04    0.045255
2021-05-05    0.385665
Freq: D, dtype: float64

In [200]:

# Slice a date range
ts['2022-01-01':'2022-01-31'].head()

2022-01-01   -0.655547
2022-01-02   -1.728279
2022-01-03    1.146128
2022-01-04   -1.321540
2022-01-05   -0.530279
Freq: D, dtype: float64

In [201]:
ts.index.year

Index([2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020,
       ...
       2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022],
      dtype='int32', length=1000)

In [202]:
ts.index.month_name()

Index(['January', 'January', 'January', 'January', 'January', 'January',
       'January', 'January', 'January', 'January',
       ...
       'September', 'September', 'September', 'September', 'September',
       'September', 'September', 'September', 'September', 'September'],
      dtype='object', length=1000)

In [203]:
ts.index.day_name()

Index(['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday', 'Wednesday', 'Thursday', 'Friday',
       ...
       'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 'Monday'],
      dtype='object', length=1000)

In [204]:
# Create a datetime Series
dates = pd.Series(pd.to_datetime(['2023-01-01', '2023-02-15', '2023-03-30']))
dates

0   2023-01-01
1   2023-02-15
2   2023-03-30
dtype: datetime64[ns]

In [205]:
dates.dt.year

0    2023
1    2023
2    2023
dtype: int32

Task 1: Using the ts time series created earlier:
+ Select all data from the second quarter of 2021.
+ Create a new column containing the name of the day of the week (e.g., 'Monday', 'Tuesday') from the index.
+ Filter out all Sundays from the dataset.

In [206]:
ts.head()

2020-01-01    1.075837
2020-01-02   -0.453008
2020-01-03   -1.384070
2020-01-04    0.742903
2020-01-05   -0.339073
Freq: D, dtype: float64

In [207]:
ts[(ts.index.quarter==2)&(ts.index.year==2021)]

2021-04-01   -1.394583
2021-04-02   -1.019669
2021-04-03    0.856844
2021-04-04    0.500677
2021-04-05    0.116712
                ...
2021-06-26    0.386148
2021-06-27   -0.539104
2021-06-28   -1.068982
2021-06-29    0.239717
2021-06-30   -0.233298
Freq: D, Length: 91, dtype: float64

In [208]:
ts

2020-01-01    1.075837
2020-01-02   -0.453008
2020-01-03   -1.384070
2020-01-04    0.742903
2020-01-05   -0.339073
                ...
2022-09-22   -1.254815
2022-09-23    0.466244
2022-09-24   -1.065034
2022-09-25   -2.206823
2022-09-26    0.437167
Freq: D, Length: 1000, dtype: float64

In [209]:
day_names = ts.index.day_name()

In [210]:
df_ts = pd.DataFrame({'Sale':ts, 'Day_names':day_names})
df_ts[df_ts['Day_names']=='Sunday']

                Sale Day_names
2020-01-05 -0.339073    Sunday
2020-01-12  0.384857    Sunday
2020-01-19 -1.087979    Sunday
2020-01-26 -1.063031    Sunday
2020-02-02  0.793538    Sunday
...              ...       ...
2022-08-28 -1.086830    Sunday
2022-09-04 -0.873381    Sunday
2022-09-11  1.367361    Sunday
2022-09-18 -0.907756    Sunday
2022-09-25 -2.206823    Sunday

[143 rows x 2 columns]

In [211]:
#Tasks 2:
df_sales = pd.DataFrame({
    'date': ['2023-01-29', '2023-01-30', '2023-02-01', '2023-02-02', '2023-02-03'],
    'sales': [250, 275, 310, 290, 350]})
df_sales

         date  sales
0  2023-01-29    250
1  2023-01-30    275
2  2023-02-01    310
3  2023-02-02    290
4  2023-02-03    350

1. Prepare the Data: Convert the date column to datetime objects and then set this column as the DataFrame's index.
2. Monthly Analysis: Select all sales data for February 2023. Calculate the total sales for that month.
3. Feature Engineering: Create a new column called day_of_week that contains the name of the day for each sale date.
4. Business Insight: Calculate the average sales for each day of the week to find out which day is the most profitable based on this small sample. (Hint: df.groupby('day_of_week')['sales'].mean()).

In [212]:
df_sales['date'] = pd.to_datetime(df_sales['date'])
df_sales.set_index('date', inplace=True)
df_sales

            sales
date
2023-01-29    250
2023-01-30    275
2023-02-01    310
2023-02-02    290
2023-02-03    350

In [213]:
df_sales[df_sales.index.month_name()=='February'].sum()

sales    950
dtype: int64

In [214]:
df_sales

            sales
date
2023-01-29    250
2023-01-30    275
2023-02-01    310
2023-02-02    290
2023-02-03    350

In [215]:
df_sales['Day of week'] = df_sales.index.day_of_week
df_sales

            sales  Day of week
date
2023-01-29    250            6
2023-01-30    275            0
2023-02-01    310            2
2023-02-02    290            3
2023-02-03    350            4

In [216]:
df_sales.groupby('Day of week').mean()

             sales
Day of week
0            275.0
2            310.0
3            290.0
4            350.0
6            250.0

1. Load and Clean Data
Load the OnlineRetail.csv file.
Remove rows with missing CustomerID.
Convert the InvoiceDate column to the datetime data type.

In [217]:
df = pd.read_excel('Online_Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [225]:
df.dropna(subset='CustomerID', inplace = True)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [229]:
df['InvoceDate'] = pd.to_datetime(df['InvoiceDate'], errors = 'coerce')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoceDate
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010-12-01 08:26:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01 08:26:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010-12-01 08:26:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01 08:26:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010-12-01 08:26:00

2. Time Analysis
Create an Hour column (hour of the day) from InvoiceDate.
Analyze which hour of the day has the most transactions.

In [232]:
df['hour'] = df['InvoiceDate'].dt.hour
df['hour'].head()

0    8
1    8
2    8
3    8
4    8
Name: hour, dtype: int32

In [239]:
most_transaction_hour = df.groupby('hour').agg({'InvoiceNo': 'nunique'})
most_transaction_hour

      InvoiceNo
hour
6            22
7            31
8           608
9          1622
10         2613
11         2770
12         3597
13         3043
14         2645
15         2405
16         1491
17          842
18          257
19          217
20           28

In [243]:
most_transaction_hour.sort_values(by = 'InvoiceNo', ascending=False).iloc[0]

InvoiceNo    3597
Name: 12, dtype: int64

3. Text Analysis
Normalize the Description column by converting it to lowercase.
Create a boolean column named IsCoffeeRelated which is True if the product description contains the word "coffee".
Calculate the total revenue (Quantity * UnitPrice) for "coffee" related products and compare it with other products.


4. Combined Analysis
Filter for transactions that occurred in December.
Within December, which product related to "gift" or "christmas" was sold the most (by quantity)?